# Generated by Django 4.0.6 on 2022-10-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='siteaddress',
        ),
        migrations.AddField(
            model_name='question',
            name='address',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
