# Generated by Django 4.0.6 on 2022-11-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0003_answer_author_question_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_modify',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_modify',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
